// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package eventlog

import (
	"encoding/json"
	"errors"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*finalizedExitEventMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (f FinalizedExitEvent) MarshalJSON() ([]byte, error) {
	type FinalizedExitEvent struct {
		Exiter       common.Address `json:"exiter"         gencodec:"required"`
		DepositIndex hexutil.Uint64 `json:"depositIndex"   gencodec:"required"`
		Denomination hexutil.Uint64 `json:"denomination"   gencodec:"required"`
		TokenID      hexutil.Uint64 `json:"tokenID"        gencodec:"required"`
		TS           hexutil.Uint64 `json:"timestamp"      gencodec:"required"`
	}
	var enc FinalizedExitEvent
	enc.Exiter = f.Exiter
	enc.DepositIndex = hexutil.Uint64(f.DepositIndex)
	enc.Denomination = hexutil.Uint64(f.Denomination)
	enc.TokenID = hexutil.Uint64(f.TokenID)
	enc.TS = hexutil.Uint64(f.TS)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (f *FinalizedExitEvent) UnmarshalJSON(input []byte) error {
	type FinalizedExitEvent struct {
		Exiter       *common.Address `json:"exiter"         gencodec:"required"`
		DepositIndex *hexutil.Uint64 `json:"depositIndex"   gencodec:"required"`
		Denomination *hexutil.Uint64 `json:"denomination"   gencodec:"required"`
		TokenID      *hexutil.Uint64 `json:"tokenID"        gencodec:"required"`
		TS           *hexutil.Uint64 `json:"timestamp"      gencodec:"required"`
	}
	var dec FinalizedExitEvent
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Exiter == nil {
		return errors.New("missing required field 'exiter' for FinalizedExitEvent")
	}
	f.Exiter = *dec.Exiter
	if dec.DepositIndex == nil {
		return errors.New("missing required field 'depositIndex' for FinalizedExitEvent")
	}
	f.DepositIndex = uint64(*dec.DepositIndex)
	if dec.Denomination == nil {
		return errors.New("missing required field 'denomination' for FinalizedExitEvent")
	}
	f.Denomination = uint64(*dec.Denomination)
	if dec.TokenID == nil {
		return errors.New("missing required field 'tokenID' for FinalizedExitEvent")
	}
	f.TokenID = uint64(*dec.TokenID)
	if dec.TS == nil {
		return errors.New("missing required field 'timestamp' for FinalizedExitEvent")
	}
	f.TS = uint64(*dec.TS)
	return nil
}
